Repository bcgov/devops-platform-workshops, pull requests merged in 2022-06, with the labels that each got.

#130 Terminology, spelling
  101-lab/content/03_deployment.md
  101-lab/content/07_autoscaling.md
  101-lab/content/10_event_streams.md
  101-lab/content/13_metrics.md
  101-lab/content/15_pod_lifecycle.md
Labels: ready for review

#129 OCP 201 - misc fixes
  openshift-201/README.md
  openshift-201/images/resource-mgmt/pod-load-cpu.png
  openshift-201/resource-mgmt.md
Labels: ready for review

#131 ocp201 - auto scaling misc fix
  .vscode/extensions.json
  .vscode/settings.json
  openshift-201/image-management.md
  openshift-201/logging.md
  openshift-201/pipelines.md
  openshift-201/post-outage-checkup.md
  openshift-201/resource-mgmt.md
  openshift-201/rh201-pod-auto-scale.md
Labels: ready for review

#132 OCP 201 Lab - Misc fix
  openshift-201/image-management.md
  openshift-201/logging.md
  openshift-201/post-outage-checkup.md
  openshift-201/rh201-pod-auto-scale.md
Labels: ready for review

#134 Create quiz.md
  openshift-201/materials/quiz.md
  openshift-201/resource-mgmt.md
Labels: ready for review, ocp-201

#133 PR for Network Policy lab material
  openshift-201/images/network-policy-acs/acs-network-graph.png
  openshift-201/network-policy.md
Labels: ocp-201
